# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericContent',
            fields=[
                ('basicPage_id', models.AutoField(primary_key=True, serialize=False)),
                ('showDate', models.BooleanField(default=False, verbose_name='Show date')),
                ('author', models.CharField(blank=True, max_length=500)),
                ('summary', mezzanine.core.fields.RichTextField(blank=True)),
                ('image', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('image_footer', mezzanine.core.fields.RichTextField(blank=True)),
                ('video_footer', mezzanine.core.fields.RichTextField(blank=True)),
                ('hostVideo', models.SmallIntegerField(blank=True, choices=[(0, b'----'), (2, b'Youtube'), (1, b'Vimeo')], default=0)),
                ('video_id', models.CharField(blank=True, help_text='The id of the video', max_length=255, null=True)),
            ],
        ),
    ]
