# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('sites', '0002_alter_domain_unique'),
        ('galleries', '0002_auto_20141227_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('question', models.CharField(max_length=300)),
                ('answer', mezzanine.core.fields.RichTextField()),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(blank=True)),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'FAQ page',
                'verbose_name_plural': 'FAQ pages',
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('featured_portfolio_heading', models.CharField(blank=True, default=b'Recent works', help_text=b'If present and featured_portfolio is set portfolio items will be shown with this header.', max_length=100)),
                ('max_portfolio_items', models.PositiveIntegerField(blank=True, default=6, help_text=b'The maximum number of items from the above selected portoflio to show.', null=True)),
                ('icon_box_layout', models.CharField(choices=[(b'TW', b'Two across'), (b'TH', b'Three across'), (b'TB', b'Three across boxes')], default=b'TH', max_length=2)),
                ('recent_blog_heading', models.CharField(blank=True, default=b'Latest blog posts', help_text=b'If present recent blog posts will be shown', max_length=100)),
                ('breakout_heading', models.CharField(blank=True, max_length=200)),
                ('breakout_content', mezzanine.core.fields.RichTextField(blank=True)),
                ('breakout_button_text', models.CharField(blank=True, max_length=200)),
                ('breaktou_button_link', models.CharField(blank=True, max_length=2000)),
                ('featured_gallery_heading', models.CharField(blank=True, default=b'Our clients', help_text=b'If present and featured_gallery is selected a carousel of the gallery images will be shown with this title.', max_length=100)),
                ('featured_gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galleries.Gallery')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Home page',
                'verbose_name_plural': 'Home pages',
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='IconBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('icon', models.CharField(help_text=b'Enter the name of a font awesome icon, i.e. fa-eye. A list is available here http://fontawesome.io/', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', mezzanine.core.fields.RichTextField()),
                ('link', models.CharField(blank=True, help_text=b'Optional, if provided clicking the box will go here.', max_length=2000)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='theme.HomePage')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('columns', models.CharField(choices=[(b'6', b'Two columns'), (b'4', b'Three columns'), (b'3', b'Four Columns')], default=b'3', max_length=1)),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('layout', models.PositiveIntegerField(choices=[(1, b'Slideshow/video above, content below'), (2, b'Slideshow/video on left, content on right'), (3, b'Slideshow/video on right, content on left')], default=1)),
                ('description_heading', models.CharField(default=b'Project description', max_length=200)),
                ('featured_image', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Featured Image')),
                ('featured_video', models.TextField(blank=True, help_text=b'Optional, putting video embed code (iframe) here, will override a Featured image specified above.  This has been tested to work with Youtube and Vimeo, but may work with other iframes as well.')),
                ('details_heading', models.CharField(default=b'Project details', max_length=200)),
                ('website', models.CharField(blank=True, help_text=b'A link to the finished project or clients website  (optional)', max_length=2000)),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Portfolio item',
                'verbose_name_plural': 'Portfolio items',
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='PortfolioItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, null=True, verbose_name='URL')),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'Portfolio Item Category',
                'verbose_name_plural': 'Portfolio Item Categories',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('portfolioitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='theme.PortfolioItem')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
        migrations.CreateModel(
            name='PortfolioItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('file', mezzanine.core.fields.FileField(max_length=200, verbose_name='File')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('portfolioitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='theme.PortfolioItem')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_scheme', models.PositiveIntegerField(default=3, help_text=b'Use the cog icon in the front end to try out color schemes.')),
                ('sidebar_alignment', models.CharField(choices=[(b'LE', 'Left'), (b'RI', 'Right')], default=b'RI', help_text=b'For pages that have a sidebar, determines if it is on the left or right', max_length=2)),
                ('default_sidebar', models.TextField()),
                ('blog_layout', models.PositiveIntegerField(choices=[(1, 'One'), (2, 'Two')], default=2, help_text=b'Determines how many blog posts are shown per row in the blog list view')),
                ('footer_description', mezzanine.core.fields.RichTextField()),
                ('footer_blog_heading', models.CharField(default=b'Recent posts', max_length=100)),
                ('footer_menu_heading', models.CharField(default=b'Popular pages', max_length=100)),
                ('footer_flickr_heading', models.CharField(default=b'Flickr photos', max_length=100)),
                ('footer_flickr_content', mezzanine.core.fields.RichTextField(blank=True, help_text=b'If present will override the flickr widget in the footer')),
                ('contact_iframe', models.TextField(blank=True, help_text=b"If present any form with slug contact will displayed with a custom template that has this iframe at the top. i.e. add a Google Map's iframe here.")),
                ('contact_iframe_layout', models.CharField(blank=True, choices=[(b'FULL', 'Full width'), (b'PAGE', 'Page width')], default=b'FULL', max_length=4)),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('background', mezzanine.core.fields.FileField(blank=True, max_length=255, verbose_name='Background Image')),
                ('heading', models.CharField(blank=True, max_length=100)),
                ('subheading', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True, help_text=b'Add <br> for line breaks')),
                ('button_text', models.CharField(blank=True, help_text=b'Optional, if present a button with the link specified below will be in the slide', max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=2000)),
                ('image', mezzanine.core.fields.FileField(blank=True, max_length=255, verbose_name='Image')),
                ('custom', models.TextField(blank=True, help_text=b'Create a custom slide, everything else will be overriden')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='theme.HomePage')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='portfolioitems', to='theme.PortfolioItemCategory', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='related_items',
            field=models.ManyToManyField(blank=True, related_name='_portfolioitem_related_items_+', to='theme.PortfolioItem'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.Portfolio'),
        ),
        migrations.AddField(
            model_name='faq',
            name='faqpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='theme.FAQPage'),
        ),
    ]
