# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-30 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Foro',
        ),
    ]
