# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 12:54
from __future__ import unicode_literals

import Welpe.actividades.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('basicModels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('genericcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='basicModels.GenericContent')),
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('destacado', models.BooleanField(default=False, verbose_name='Es una actividad destacada')),
                ('url', models.TextField(blank=True, default='', max_length=500)),
                ('descripcion', mezzanine.core.fields.RichTextField()),
                ('limite_participantes', models.BooleanField(default=False, verbose_name='limit participants')),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('lugar', models.TextField(blank=True, max_length=500)),
                ('creditos_rac', models.BooleanField(default=False, verbose_name='Se conceden RAC')),
                ('n_rac', models.IntegerField(blank=True, null=True)),
                ('adminlist', models.TextField(blank=True, max_length=500)),
                ('permitir_inscriptions', models.BooleanField(default=False, verbose_name='Permitir inscripciones')),
                ('fecha_inscripcion_inicio', models.DateField(blank=True, null=True)),
                ('fecha_inscripcion_final', models.DateField(blank=True, null=True)),
                ('lista_espera', models.BooleanField(default=False, verbose_name='Permitir lista de espera')),
                ('enviar_notificaciones', models.BooleanField(default=True, verbose_name='Enviar notificaciones')),
                ('email_organizador', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email to receive notifications')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to=Welpe.actividades.models.user_directory_actividades, verbose_name='Attach an file')),
                ('incluir_miniactividades', models.BooleanField(default=True, verbose_name='Incluir MiniActividades')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_date',),
                'verbose_name': 'Actividades',
                'verbose_name_plural': 'Lista de Actividades',
            },
            bases=('pages.page', 'basicModels.genericcontent', models.Model),
        ),
        migrations.CreateModel(
            name='AsistentesMiniActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=150)),
                ('comentario', mezzanine.core.fields.RichTextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.Actividades')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='CommentsMiniActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=150)),
                ('comentario', mezzanine.core.fields.RichTextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='MiniActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=510)),
                ('descripcion', mezzanine.core.fields.RichTextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=Welpe.actividades.models.user_directory_miniactividades)),
                ('place', models.CharField(blank=True, max_length=500)),
                ('fecha', models.TextField(blank=True, max_length=500)),
                ('hora', models.TextField(blank=True, max_length=500)),
                ('is_keynote', models.BooleanField(default=False)),
                ('add_sep', models.BooleanField(default=False)),
                ('creditos_rac', models.BooleanField(default=False, verbose_name='Se conceden RAC')),
                ('n_rac', models.IntegerField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.Actividades')),
            ],
            options={
                'verbose_name': 'Mini-actividad',
                'verbose_name_plural': 'Lista de mini-actividades',
            },
        ),
        migrations.CreateModel(
            name='OrganizadorMiniActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', mezzanine.core.fields.RichTextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('photo', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Photo')),
                ('miniactividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.MiniActividad')),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosListaEsperaActividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.IntegerField()),
                ('dni', models.CharField(max_length=15)),
                ('titulacion', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.Actividades')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosRegistradosActividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.IntegerField()),
                ('dni', models.CharField(max_length=15)),
                ('titulacion', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.Actividades')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commentsminiactividad',
            name='miniactividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.MiniActividad'),
        ),
        migrations.AddField(
            model_name='commentsminiactividad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistentesminiactividad',
            name='miniactividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.MiniActividad'),
        ),
        migrations.AddField(
            model_name='asistentesminiactividad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
