# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniactividad',
            name='add_sep',
        ),
        migrations.RemoveField(
            model_name='miniactividad',
            name='is_keynote',
        ),
    ]
