# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-02 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_auto_20161210_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioslistaesperaactividades',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='usuarioslistaesperaactividades',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='usuarioslistaesperaactividades',
            name='titulacion',
        ),
        migrations.RemoveField(
            model_name='usuariosregistradosactividades',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='usuariosregistradosactividades',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='usuariosregistradosactividades',
            name='titulacion',
        ),
    ]
