# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_auto_20170402_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsactividad',
            name='anonimo',
            field=models.BooleanField(default=False),
        ),
    ]
