# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-25 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='formacion',
            field=models.TextField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='investigacion',
            field=models.TextField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
