# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20170325_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_skype',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='institucion',
        ),
    ]
