# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_remove_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pagina_web',
            field=models.TextField(max_length=50),
        ),
    ]
