# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20170403_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pagina_web',
            field=models.URLField(),
        ),
    ]
