# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-01 09:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0011_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.TextField(blank=True, max_length=150)),
                ('curso', models.IntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.TextField(max_length=150)),
                ('puesto', models.TextField(max_length=150)),
                ('formacion', models.TextField(max_length=150)),
                ('investigacion', models.TextField(max_length=150)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='formacion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='investigacion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='puesto',
        ),
    ]
