# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-01 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_auto_20170501_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=mezzanine.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dni',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pagina_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profilealumno',
            name='curso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileprofesor',
            name='departamento',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profileprofesor',
            name='formacion',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profileprofesor',
            name='investigacion',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profileprofesor',
            name='puesto',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
