# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-29 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0013_auto_20170501_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='show_email',
        ),
    ]
