# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 12:54
from __future__ import unicode_literals

import Welpe.propuestas.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('basicModels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsPropuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=150)),
                ('comentario', mezzanine.core.fields.RichTextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='Propuestas',
            fields=[
                ('genericcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='basicModels.GenericContent')),
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', mezzanine.core.fields.RichTextField()),
                ('dni', models.CharField(max_length=15)),
                ('curso', models.IntegerField()),
                ('titulacion', models.CharField(max_length=150)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=Welpe.propuestas.models.user_directory)),
                ('estado_propuesta', models.SmallIntegerField(choices=[(0, 'Enviado'), (1, 'Aceptado'), (2, 'Rechazado')], default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page', 'basicModels.genericcontent', models.Model),
        ),
        migrations.AddField(
            model_name='commentspropuesta',
            name='propuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propuestas.Propuestas'),
        ),
        migrations.AddField(
            model_name='commentspropuesta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
