# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0002_remove_propuestas_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuestas',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='propuestas',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='propuestas',
            name='titulacion',
        ),
        migrations.AddField(
            model_name='propuestas',
            name='titulo',
            field=models.TextField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
