# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0003_auto_20170401_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentspropuesta',
            name='anonimo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propuestas',
            name='anonimo',
            field=models.BooleanField(default=False),
        ),
    ]
