# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0004_auto_20170401_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuestas',
            name='anonimo',
        ),
    ]
