# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 12:54
from __future__ import unicode_literals

import Welpe.ofertaTrabajo.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('basicModels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsOferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=150)),
                ('comentario', mezzanine.core.fields.RichTextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='OfertaTrabajo',
            fields=[
                ('genericcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='basicModels.GenericContent')),
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('descripcion', mezzanine.core.fields.RichTextField()),
                ('como_aplicar', mezzanine.core.fields.RichTextField()),
                ('cuando', models.CharField(blank=True, max_length=150)),
                ('donde', models.CharField(blank=True, max_length=150)),
                ('url', models.URLField()),
                ('salario', models.CharField(blank=True, max_length=150)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to=Welpe.ofertaTrabajo.models.user_directory_ofertas, verbose_name='Fichero Adjunto')),
                ('tipo_contrato', models.SmallIntegerField(choices=[(0, 'Pr\xe1cticas'), (1, 'Indefinido'), (2, 'Otros')], default=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Listado de Ofertas',
            },
            bases=('pages.page', 'basicModels.genericcontent', models.Model),
        ),
        migrations.AddField(
            model_name='commentsoferta',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofertaTrabajo.OfertaTrabajo'),
        ),
        migrations.AddField(
            model_name='commentsoferta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
